# MQ的服务器地址
spring:
  activemq:
    in-memory: false
    user: admin
    password: admin
    broker-url: tcp://127.0.0.1:61616
    pool:
      enabled: true
    max-connections: 100
server:
  port: 8080